### ISSUE TITLE
legacy OTN dataset registration 1

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#70]
from #45 as suggested by @bmaitner 
```
-
    Timestamp: 6/25/2019 14:45:39
    datasetDOI_URL: http://ecotaxonomy.org
    contactName: Anton Potapov | Dorothee Sandmann | Stefan Scheu
    contactEmail: potapov.msu@gmail.com
    license: http://creativecommons.org/licenses/by-nc/4.0/
    traitList: Multiple morphological and ecological traits 
    higherGeography: Global | Sumatra | Ecuador | Canada | Europe
    decimalLatitude: 
    decimalLongitude: 
    taxon: Animalia | Arthropoda | Arachnida | Insecta | Myriapoda | Araneae | Collembola | Oribatida | Mesostigmata | Formicidae
    eventDate: 
    paperDOIcitation: 10.3897/biss.3.37146
    description: "Ecotaxonomy (ecotaxonomy.org), is an open web platform, that allows traits, taxa, individuals and samples to be linked within research projects. Any morphological or ecological traits can be customized inside the system and attached either to taxa, individuals, or environmental samples. The system is flexible to include any group of organisms. The taxonomic system of Ecotaxonomy is based on the Global Biodiversity Information Facility (gbif.org), but may be complemented by morphospecies, pictures, literature and other parameters. As public output, the system provides interactive\nidentification keys and web catalogs of traits and taxa."
    taxaList: Multiple groups of organisms (focused on Arthropoda)
    usefulClasses: morphology, inferred traits, ecological traits, taxonomic traits, individual traits
    dataStandard: Internal standards will be linked to Darwin Core and Ecological Trait-Data Standard via API interface
    standardizationScripts: 
    datasetName: Ecotaxonomy
    datasetID: 
-
    Timestamp: 8/22/2019 15:03:02
    datasetDOI_URL: https://doi.org/10.6084/m9.figshare.4644424
    contactName: Brunno Freire Oliveira | Gabriel C. Costa
    contactEmail: 
    license: CC BY 4.0
    traitList: Habitat | Diet | Circadian_activity_rhythm | Seasonality | Body_weight | Age_at_mature_min_y | Age_at_mature_max_y | Body_length | Size_at_mature_min_mm | Size_at_mature_max_mm | Longevity_min_y | Longevity_max_y | Litter_size_min_n | Litter_size_max_n | Reproductive_output_y | Offspring_size_min_mm | Offspring_size_min_mm | Breeding strategy
    higherGeography: Africa | Asia | Europe | North America | Oceania | South America
    decimalLatitude: 
    decimalLongitude: 
    taxon: Amphibia
    eventDate: 
    paperDOIcitation: 10.1038/sdata.2017.123
    description: Global database for amphibian ecological traits (collection of data from literature)
    taxaList: 
    usefulClasses: literatureData
    dataStandard: none
    standardizationScripts: 
    datasetName: AmphiBio
    datasetID: 
-
    Timestamp: 8/22/2019 15:18:05
    datasetDOI_URL: https://doi.org/10.3897/BDJ.2.e4123
    contactName: Audrey Trochet
    contactEmail: 
    license: CC-0
    traitList: Body_weight | Male_body_length | Female_body_length | Body_length | Foot length | Tibia length | Hind limb length | Metamorphosis size | Number of eggs | Survival rates in adults | Sexual maturity | Movement ability
    higherGeography: Europe
    decimalLatitude: 
    decimalLongitude: 
    taxon: Amphibia
    eventDate: 
    paperDOIcitation: https://doi.org/10.3897/BDJ.2.e4123
    description: A database of life-history traits of European amphibians (collection of data from literature)
    taxaList: 
    usefulClasses: literatureData
    dataStandard: none
    standardizationScripts: 
    datasetName: European Amphibian Traits Trochet
    datasetID: 
```
