### ISSUE TITLE
legacy OTN dataset registration 2

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#71]
legacy OTN dataset registration 2
from #45 as suggested by @bmaitner

```
-
    Timestamp: 8/26/2019 16:25:08
    datasetDOI_URL: https://doi.org/10.5061/dryad.53ds2
    contactName: Martin M Gossner
    contactEmail: 
    license: CC BY 4.0
    traitList: Body_size | Dispersal_ability | Feeding_guild | Feeding_mode | Feeding_specialization | Feeding_tissue | Feeding_plant_part | Endophagous_lifestyle | Stratum_use | 
    higherGeography: Germany
    decimalLatitude: 
    decimalLongitude: 
    taxon: Arthropod
    eventDate: 2008 | 2009 | 2010 | 2011 | 2012
    paperDOIcitation: doi: 10.1038/sdata.2015.13
    description: A summary of eight traits of Coleoptera, Hemiptera, Orthoptera and Araneae, occurring in grasslands in Germany
    taxaList: Coleoptera | Hemiptera | Orthoptera | Araneae
    usefulClasses: adult, sweep-netting
    dataStandard: 
    standardizationScripts: 
    datasetName: German Grassland Arthropods Traits Gossner
    datasetID: 
-
    Timestamp: 8/26/2019 16:32:23
    datasetDOI_URL: https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.1783
    contactName: Robert E. Ricklefs
    contactEmail: 
    license: CC0
    traitList: Body_length | Wing_length | Tail_length | Tarsus_length | Toe_length | Bill_length | Bill_width | Bill_depth | Biogeographic_region
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Passerine
    eventDate: 
    paperDOIcitation:  https://doi.org/10.1002/ecy.1783
    description: Passerine morphology: external measurements of approximately one‐quarter of passerine bird species
    taxaList: 
    usefulClasses: museum specimens
    dataStandard: 
    standardizationScripts: 
    datasetName: Global Passerine Morphology Ricklefs
    datasetID: 
-
    Timestamp: 8/28/2019 10:33:07
    datasetDOI_URL: https://www.try-db.org
    contactName: Jens Kattge
    contactEmail: jkattge@bgc-jena.mpg.de
    license: CC BY 
    traitList: 2091 plant traits, standardized according to http://top-thesaurus.org
    higherGeography: Global | Africa | Antarctica | Asia | Europe | North America | Oceania | South America
    decimalLatitude: 
    decimalLongitude: 
    taxon: Tracheophyta
    eventDate: about 1900 to current
    paperDOIcitation: 10.1111/j.1365-2486.2011.02451.x
    description: A database of databases for vascular plant traits, terrestrial and fresh-water.
    taxaList: 279,875 plant taxa, standardized mainly based on The Plant List
    usefulClasses: Mostly in-situ measurements on plant individuals
    dataStandard: Standardization of traits according to: http://top-thesaurus.org/; standardization of taxonomy mainly based on: http://www.theplantlist.org/
    standardizationScripts: https://www.try-db.org/TryWeb/Database.php
    datasetName: TRY
    datasetID:
```
