### ISSUE TITLE
legacy OTN dataset registration 3

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#72]
legacy OTN dataset registration 3
from #45 as suggested by @bmaitner
 
```
-
    Timestamp: 8/28/2019 17:18:01
    datasetDOI_URL: http://www.compadre-db.org/
    contactName: Rob Salguero-Gómez
    contactEmail: rob.salguero@zoo.ox.ac.uk
    license: CC-BY
    traitList: Survival | Development | Reproduction | Recruitment | and many more! See here: https://github.com/jonesor/compadreDB
    higherGeography: Continent | Country | Ecoregion | Lat | Lon
    decimalLatitude: -90
    decimalLongitude: -180
    taxon: Comprehensive coverage of plants (COMPADRE) and animals (COMADRE)
    eventDate: From 1945 to date
    paperDOIcitation: https://doi.org/10.1111/1365-2745.12334 | https://doi.org/10.1111/1365-2656.12482
    description: Demographic, taxonomic, biogeographic and phylogenetic information of thousand of plants and animals
    taxaList: Plantae and Animalia
    usefulClasses: Life stage, life history trait, vital rate, population growth rate
    dataStandard: 
    standardizationScripts: https://github.com/jonesor/compadreDB
    datasetName: Compadre
    datasetID: 
-
    Timestamp: 8/28/2019 18:58:23
    datasetDOI_URL: https://cran.r-project.org/web/packages/BIEN/index.html
    contactName: Brian J. Enquist | Brad Boyle | Cory Merow | Xiao Feng | Dan Park |Brian S. Maitner | BIEN working group
    contactEmail: bmaitner@gmail.com
    license: CC BY-NC-ND
    traitList: 53 plant traits
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Embryophyta
    eventDate: 
    paperDOIcitation: https://doi.org/10.1111/2041-210X.12861
    description: 
    taxaList: 
    usefulClasses: Aggregated data, primarily from published datasets
    dataStandard: 
    standardizationScripts: 
    datasetName: BIEN
    datasetID: 
-
    Timestamp: 8/29/2019 17:36:16
    datasetDOI_URL: http://www.esapubs.org/archive/ecol/E088/096/default.htm
    contactName: Terje Lislevand
    contactEmail: 
    license: CC BY 4.0
    traitList: "M_mass | M_mass_N | F_mass | F_mass_N | Unsexed_mass | Unsexed_mass_N | M_wing | M_wing_N | F_wing | F_wing_N | Unsexed_wing | Unsexed_wing_N | M_tarsus | M_tarsus_N | F_tarsus | F_tarsus_N | Unsexed_tarsus | Unsexed_tarsus_N | M_bill | M_bill_N | F_bill | F_bill_N | Unsexed_bill | Unsexed_bill_N | M_tail  | M_tail_N | F_tail | F_tail_N | Unsexed_tail  | Unsexed_tail_N | Clutch_size | Egg_mass | Mating_System | Display | Resource \n"
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Aves
    eventDate: 
    paperDOIcitation: http://www.esapubs.org/archive/ecol/E088/096/default.htm
    description: Avian body sizes in relation to fecundity, mating system, display behavior, and resource sharing
    taxaList: 
    usefulClasses: literatureData
    dataStandard: 
    standardizationScripts: 
    datasetName: Global Avian Traits Lislevand 
    datasetID: 
```
