### ISSUE TITLE
legacy OTN dataset registration 4

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#73]
legacy OTN dataset registration 4
from #45 as suggested by @bmaitner

```
-
    Timestamp: 8/29/2019 17:42:27
    datasetDOI_URL: http://www.esapubs.org/archive/ecol/E095/178/
    contactName: Walter Jetz
    contactEmail: 
    license: CC BY 4.0
    traitList: Diet | Foraging_stratum | Nocturnal | Body_mass
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Aves | Mammalia
    eventDate: 
    paperDOIcitation: 10.1890/13-1917.1
    description: 'EltonTraits 1.0: Species-level foraging attributes of the world''s birds and mammals'
    taxaList: 
    usefulClasses: literatureData
    dataStandard: 
    standardizationScripts: 
    datasetName: EltonTraits
    datasetID: 
-
    Timestamp: 8/29/2019 22:16:50
    datasetDOI_URL: https://figshare.com/articles/Catching_crabs_a_case_study_in_local_scale_English_conservation/979288
    contactName: Will Pearse
    contactEmail: will.pearse@gmail.com
    license: CCBY4
    traitList: diameter|sex
    higherGeography: Europe | United Kingdom | England | Norfolk | Wells-next-the-Sea
    decimalLatitude: 52.95
    decimalLongitude: 0.85
    taxon: Carcinus maenas
    eventDate: 2007-08
    paperDOIcitation: arXiv:1404.0290
    description: 
    taxaList: Carcinus maenas
    usefulClasses: carapace
    dataStandard: 
    standardizationScripts: https://github.com/willpearse/MADtraits/blob/master/R/downloads.R#L1180
    datasetName: Norfolk Carcinus maenas Pearse
    datasetID: 
-
    Timestamp: 9/4/2019 6:01:22
    datasetDOI_URL: https://doi.org/10.6084/m9.figshare.7996328.v2
    contactName: J. Aaron Hogan
    contactEmail: jamesaaronhogan@gmail.com
    license: CC by 4.0
    traitList: "Leaf Area | LeafPermiter | LeafWidth | LeafHeight | LeafCircularity | LeafAspectRatio | LeafRoundness | LeafMass | SLA | LeafThickness | RootMass |\nRootLength | SpecificRootLength | RootProjArea | RootArea | SpecifcRootArea | RootAvgDiam | RootLenPerVol | RootVolume | RootTD | NRootTips  | SRTipAbund   NForks  | NCrossings."
    higherGeography: Asia | China | Hainan Island | Jianfengling Forest Reserve 
    decimalLatitude: 
    decimalLongitude: 
    taxon: Plantae | Angiosperms
    eventDate: May - June 2017
    paperDOIcitation:  https://doi.org/10.1101/611640
    description: 
    taxaList: 
    usefulClasses: plant root and leaf traits, tropical trees
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
```
