### ISSUE TITLE
legacy OTN dataset registration 5

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#74]
legacy OTN dataset registration 5
from #45 as suggested by @bmaitner

```
-
    Timestamp: 9/4/2019 18:43:54
    datasetDOI_URL: http://polytraits.lifewatchgreece.eu/polytraits
    contactName: Sarah Faulwetter
    contactEmail: 
    license: Creative Commons Attribution 3.0
    traitList: broad range, ~60 traits
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Polychaeta
    eventDate: 
    paperDOIcitation: doi:10.3897/BDJ.2.e1024
    description: A database on biological traits of polychaetes
    taxaList: 
    usefulClasses: adult|larval
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/5/2019 2:25:20
    datasetDOI_URL: http://globalants.org/
    contactName: Heloise Gibb
    contactEmail: h.gibb@latrobe.edu.au
    license: We have a "Terms of Use" document modelled on TRY
    traitList: "Head.width.across.eyes..mm|Head.length..mm|Clypeus.length..mm|\tMandible.length..mm|Hind.femur.length..mm|Scape.length..mm|\tWeber.s.length..mm|Pronotum.width..mm|Inter.ocular.width..mm|\tMax.eye.width..mm|Whole.body.length..mm|Sculpturing|Pilosity|Number.of.Spines|Dominant.colour.head..Fig..16|Dominant.colour.mesosoma..Fig..16|Dominant.colour.gaster..Fig..16|Polymorphism|Queen.number|Worker.number|Colony.type|Colony.founding|Nest.Site|Activity|Diet\n"
    higherGeography: Multiple levels - from Continent to local
    decimalLatitude: -42.7
    decimalLongitude: -171.8
    taxon: Formicidae (ants)
    eventDate: 1949-2014
    paperDOIcitation: Parr, C. L., Dunn, R. R., Sanders, N. J., Weiser, M. D., Photakis, M., Bishop, T. R., ... & Gibb, H. (2017). GlobalAnts: a new database on the geography of ant traits (Hymenoptera: Formicidae). Insect Conservation and Diversity, 10(1), 5-20.
    description: Part of a database that also includes assemblage and abundance data for ants
    taxaList: Formicidae - should discuss how you want this as we have localised morphospecies in a lot of datasets
    usefulClasses: worker ants
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/5/2019 11:37:39
    datasetDOI_URL: https://doi.pangaea.de/10.1594/PANGAEA.862968
    contactName: Philipp Brun
    contactEmail: 
    license: CC BY 3.0
    traitList: Body_size | Feeding_mode | Clearance_rates | Ingestion_rates | Spawning_strategy | Egg_size | Clutch_size | Fecundity | Myelination | Hibernation | Resting_eggs | Respiration_rates | Growth_rates | Development_duration
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: copepods
    eventDate: 
    paperDOIcitation: https://doi.org/10.5194/essd-9-99-2017, 2017
    description: A trait database for marine copepods
    taxaList: 
    usefulClasses: literatureData, expertKnowledge
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
```
