### ISSUE TITLE
legacy OTN dataset registration 6

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#75]
legacy OTN dataset registration 6
from #45 as suggested by @bmaitner

```
-
    Timestamp: 9/5/2019 11:45:23
    datasetDOI_URL: http://genomics.senescence.info/species/
    contactName: João Pedro de Magalhães
    contactEmail: 
    license: CC BY 3.0
    traitList: Female maturity | Male maturity | Gestation/Incubation | Weaning | Litter/Clutch size | Litters/Clutches per year| Inter-litter/Interbirth interval | Birth weight | Weaning weight | Adult weight | Growth rate | Maximum longevity | IMR | MRDT  | Metabolic rate | Body mass | Temperature
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Animalia
    eventDate: 
    paperDOIcitation: 10.1093/nar/gkx1042
    description: AnAge Database of Animal Ageing and Longevity
    taxaList: 
    usefulClasses: literatureData, observationalData
    dataStandard: 
    standardizationScripts: 
    datasetName: AnAge
    datasetID: 
-
    Timestamp: 9/13/2019 1:58:51
    datasetDOI_URL: https://media.nature.com/original/nature-assets/ncomms/2017/170801/ncomms16047/extref/ncomms16047-s14.xlsx
    contactName: Hervé Sauquet | Jürg Schönenberger
    contactEmail: herve.sauquet@rbgsyd.nsw.gov.au
    license: CC BY 4.0
    traitList: Sex | Ovary_position | Number_of_perianth_parts | Fusion_of_perianth | Symmetry_of_perianth | Perianth_phyllotaxy | Number_of_perianth_whorls | Perianth_merism | Perianth_differentiation | Number_of_fertile_stamens | Filament | Anther_orientation | Anther_attachment | Anther_dehiscence | Androecium_structural_phyllotaxy | Number_of_androecium_structural_whorls | Androecium_structural_merism | Gynoecium_phyllotaxy | Number_of_structural_carpels | Fusion_of_ovaries | Number_of_ovules_per_functional_carpel
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Angiospermae
    eventDate: 
    paperDOIcitation: 10.1038/ncomms16047
    description: Dataset of angiosperm floral traits (mostly structural), extracted from the PROTEUS database and built for the eFLOWER project; for more information on PROTEUS and eFLOWER, see www.eflower.org
    taxaList: 792 angiosperm species
    usefulClasses: literatureData
    dataStandard: 
    standardizationScripts: 
    datasetName: Proteus eFlower
    datasetID: 
-
    Timestamp: 9/17/2019 4:52:57
    datasetDOI_URL: https://doi.org/10.6084/m9.figshare.1499292
    contactName: Stephen Garnett
    contactEmail: stephen.garnett@cdu.edu.au
    license: CC BY 4.0
    traitList: Distribution | Morphology | Habitat | Food | Behaviour | Breeding | Mobility | Climate metrics
    higherGeography: Australia
    decimalLatitude: 
    decimalLongitude: 
    taxon: Aves
    eventDate: 
    paperDOIcitation: doi:10.1038/sdata.2015.61
    description: Traits for all Australian birds
    taxaList: 
    usefulClasses: Adult
    dataStandard: None
    standardizationScripts: None
    datasetName: 
    datasetID:
```
