### ISSUE TITLE
legacy OTN dataset registration 7

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#76]
legacy OTN dataset registration 7
from #45 as suggested by @bmaitner 

```
-
    Timestamp: 9/17/2019 5:21:45
    datasetDOI_URL: https://doi.org/10.1111/jvs.12646
    contactName: Markus Bernhardt‐Römermann
    contactEmail: 
    license: CC-By
    traitList: "growth form | stem | shoot length | life form |  life strategy | protonema | Hyalin\nhairpoint | dominants | distribution of gametangia | seta | capsules | size of spores | spore ornamentation | fruiting | vegetative dispersal traits"
    higherGeography: Germany
    decimalLatitude: 
    decimalLongitude: 
    taxon: Embryophyta | Bryophyta
    eventDate: 
    paperDOIcitation: https://doi.org/10.1111/jvs.12646
    description: A compilation of autecological information and morphological and regenerative trait data on different stages of the life cycle of bryophytes occurring in forest ecosystems. The database contains information for 35 traits and 721 Central European bryophyte species; in total more than 23,000 trait values
    taxaList: 721 Central European bryophyte species
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 5:44:30
    datasetDOI_URL: http://doi.org/10.5061/dryad.1cv08,
    contactName: Joanne Bennett
    contactEmail: joanne.bennett@idiv.de
    license: CC-BY
    traitList: "Tmax | max_metric | error | error measure | Multiple measures | max_interval_after_LT0 | Tmax_2 | max_metric_2\terror | error measure | max_interval_before_LT100 | max_pretreatment | max_ramp | lat_max | long_max\televation_max | REF_max | location_max | N | tmin | min_metric | Multiple measures_min | min_interval_after_LT0 | tmin_2 | min_metric_2 | min_interval_before_LT100 | min_pretreatment | ramp_min\t"
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Chlorophyta | Plantae | Fungi | Animalia
    eventDate: 
    paperDOIcitation: doi: 10.1038/sdata.2018.22
    description: Thermal tolerance metrics for 2,133 species of multicellular algae, plants, fungi, and animals in 43 classes, 203 orders and 525 families from marine, intertidal, freshwater, and terrestrial realms, extracted from published studies. Updates to the data and metadata will be curated through the iDiv data portal https://idata.idiv.de/
    taxaList: Chlorophyta | Plantae | Fungi | Animalia
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 5:49:20
    datasetDOI_URL: https://doi.org/10.5061/dryad.f6t39kj
    contactName: Shai Meiri
    contactEmail: uncshai@post.tau.ac.il
    license: CC-BY
    traitList: body size | ecological | thermal biology | geographic | phylogenetic | life history data
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Reptilia
    eventDate: 
    paperDOIcitation: https://doi.org/10.1111/geb.12773
    description: Geographical, morphological, ecological, physiological and life history data for the 6,657 known species of lizards
    taxaList: Reptilia
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
```
