### ISSUE TITLE
legacy OTN dataset registration 8

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#77]
legacy OTN dataset registration 8
from #45 as suggested by @bmaitner 
```
-
    Timestamp: 9/17/2019 5:58:57
    datasetDOI_URL: http://www.esapubs.org/archive/ecol/E096/269/#data
    contactName: Nathan Myhrvold
    contactEmail: 
    license: CC-BY
    traitList: "female_maturity_d | litter_or_clutch_size_n | litters_or_clutches_per_y | adult_body_mass_g | maximum_longevity_y | gestation_d | weaning_d | birth_or_hatching_weight_g | weaning_weight_g | egg_mass_g\tincubation_d\t| fledging_age_d | longevity_y | male_maturity_d | inter_litter_or_interbirth_interval_y | female_body_mass_g | male_body_mass_g | no_sex_body_mass_g\tegg_width_mm | egg_length_mm | fledging_mass_g | adult_svl_cm\tmale_svl_cm\tfemale_svl_cm | birth_or_hatching_svl_cm | female_svl_at_maturity_cm | female_body_mass_at_maturity_g | no_sex_svl_cm | no_sex_maturity_d"
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Amniotes | Aves | Reptilia | Mammalia
    eventDate: 
    paperDOIcitation: https://doi.org/10.1890/15-0846R.1
    description: A normalized and consolidated database of up to 29 life-history parameters, containing at least one life-history parameter for 21 322 species of birds, mammals, and reptiles. In order to facilitate comparative analyses between amniote life‐history data, we created a database compiled from peer‐reviewed studies on individual species, macroecological studies of multiple species, existing life‐history databases, and other aggregated sources as well as published books and other compilations
    taxaList: Amniotes | Aves | Reptilia | Mammalia
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: http://www.esapubs.org/archive/ecol/E096/269/#data
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 6:04:17
    datasetDOI_URL: https://ars.els-cdn.com/content/image/1-s2.0-S0048969711001124-mmc1.pdf
    contactName: Ralf Schäfer
    contactEmail: 
    license: CC-BY
    traitList: reproduction type | food source | respiration mode| physiological sensitivity to salinity
    higherGeography: Australia
    decimalLatitude: 
    decimalLongitude: 
    taxon: Invertebrate families
    eventDate: 
    paperDOIcitation: https://doi.org/10.1016/j.scitotenv.2011.01.053
    description: We compiled a database on a priori selected traits for South-East Australian freshwater macroinvertebrate families
    taxaList: macroinvertebrates
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 6:16:04
    datasetDOI_URL: https://doi.org/10.1111/acv.12350
    contactName: Lucie Bland
    contactEmail: 
    license: CC-BY
    traitList: Body size | Egg number | Chela size | Chela shape | Habitat breadth | Habitat type
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Arthropoda | Crustacea | Malacostraca
    eventDate: 
    paperDOIcitation: https://doi.org/10.1111/acv.12350
    description: Data on intrinsic (biology and ecology) and extrinsic (environment and threats) factors for 450 crayfish species assessed on the IUCN Red List
    taxaList: Arthropoda | Crustacea | Malacostraca
    usefulClasses: IUCN listed taxa
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 6:20:31
    datasetDOI_URL: https://doi.pangaea.de/10.1594/PANGAEA.862968
    contactName: Phillip Brun
    contactEmail: 
    license: CC-BY
    traitList: "body size | feeding mode  | egg size | spawning strategy  | respiration rate |  \n myelination"
    higherGeography: Global | Marine
    decimalLatitude: 
    decimalLongitude: 
    taxon: Animalia | Arthropoda | Copepoda
    eventDate: 
    paperDOIcitation: 10.5194/essd-2016-30
    description: A trait database for marine copepods. We compiled trait information on marine pelagic copepods, a major group of zooplankton, from the published literature and from experts, and organised the data into a structured database. We collected 9345 records for 14 functional traits. 
    taxaList: 
    usefulClasses: Marine
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
```
