### ISSUE TITLE
legacy OTN dataset registration 9

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#78]
legacy OTN dataset registration 9
from #45 as suggested by @bmaitner 
```
-
    Timestamp: 9/17/2019 6:39:19
    datasetDOI_URL: http://www.fishbase.org/search.php
    contactName: Rainer Froese
    contactEmail: 
    license: CC-BY-NC
    traitList: biology | trophic ecology | life history
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Animalia | Chordata | Vertebrata | Fin Fish
    eventDate: 
    paperDOIcitation: http://fishbase.org/search.php
    description: FishBase is a global biodiversity information system on finfishes. It provides key facts on population dynamics for 200 major commercial species and has a wider range of data on all finfish species currently known in the world: taxonomy, biology, trophic ecology, life history, and uses
    taxaList: 33,000 fish species
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: FishBase
    datasetID: 
-
    Timestamp: 9/17/2019 6:45:58
    datasetDOI_URL: http://www.fishtraits.info/search/key/
    contactName: Emmanuel Frimpong
    contactEmail: 
    license: CC-BY
    traitList: trophic ecology | body size | reproductive ecology | life history | habitat preferences | salinity and temperature tolerances
    higherGeography: United States
    decimalLatitude: 
    decimalLongitude: 
    taxon: Chordata | Vertebrata | Fish
    eventDate: 
    paperDOIcitation:  https://doi.org/10.1577/1548-8446-34.10.487
    description: We have compiled a database of > 100 traits for 809 (731 native and 78 nonnative) fish species found in freshwaters of the conterminous United States, including 37 native families and 145 native genera.The database, named Fish Traits, contains information on four major categories of traits: (1) trophic ecology; (2) body size, reproductive ecology, and life history; (3) habitat preferences; and (4) salinity and temperature tolerances
    taxaList: Chordata | Vertebrata | Fish
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 6:53:09
    datasetDOI_URL: https://doi.org/10.6084/m9.figshare.c.3301274.v1
    contactName: Kate Jones
    contactEmail: 
    license: CC-BY
    traitList: life‐history | ecological | geographic | taxonomic
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Chordata | Mammalia 
    eventDate: 
    paperDOIcitation: https://doi.org/10.1890/08-1494.1
    description: Species‐level data set compiled for analysis of life history, ecology, and geography of all known extant and recently extinct mammals
    taxaList: Chordata | Mammalia
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
```
