### ISSUE TITLE
legacy OTN dataset registration 10

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#79]
legacy OTN dataset registration 10
from #45 as suggested by @bmaitner
```
-
    Timestamp: 9/17/2019 7:01:23
    datasetDOI_URL: https://doi.org/10.5061/dryad.bp26v20
    contactName: Søren Faurby
    contactEmail: 
    license: CC-0
    traitList: Aerial | Diet.Invertebrate | Diet.Plant | Diet.Vertebrate | Freshwater | Island.Endemicity | Life.Habit.Method | Marine | Mass.Comparison | Mass.g | Terrestrial
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Chordata | Mammalia
    eventDate: 
    paperDOIcitation: 10.1002/ecy.2443
    description: PHYLACINE, The Phylogenetic Atlas of Mammal Macroecology. This taxonomically integrated platform contains phylogenies, range maps, trait data, and threat status for all 5,831 known mammal species that lived since the last interglacial (~130,000 years ago until present)
    taxaList: 5,831 mammals
    usefulClasses: extinct taxa 
    dataStandard: 
    standardizationScripts: 
    datasetName: PHYLACINE
    datasetID: 
-
    Timestamp: 9/17/2019 7:41:16
    datasetDOI_URL: https://doi.org/10.5281/zenodo.2600338
    contactName: Carmen Galán-Acedo
    contactEmail: 
    license: CC-BY
    traitList: home range size | locomotion type | diel activity | trophic guild | body mass | habitat type | current conservation status | population trend | geographic realm
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Mamalia | Primates
    eventDate: 
    paperDOIcitation: https://doi.org/10.1038/s41597-019-0059-9
    description: A database on some important ecological traits of the world’s primates (504 species), including home range size, locomotion type, diel activity, trophic guild, body mass, habitat type, current conservation status, population trend, and geographic realm. We compiled this information through a careful review of 1,216 studies published between 1941 and 2018
    taxaList: 504 primate species
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 8:14:03
    datasetDOI_URL: http://esapubs.org/archive/ecol/E082/042/appendix-A.htm
    contactName: Diana Fisher
    contactEmail: 
    license: CC-BY
    traitList: Adult female mass | Age at weaning | arboreality | diet type | diurnality | Female age at maturity | Gestation length | Inter-birth interval | Litter size | Mass at birth | Mass at pouch vacation | Mass at weaning | Maximum lifespan | Mean group size | Population density | shelter type
    higherGeography: Australia | Papua New Guinea | South America
    decimalLatitude: 
    decimalLongitude: 
    taxon: Mammalia | Marsupials
    eventDate: 
    paperDOIcitation: https://doi.org/10.1890/0012-9658(2001)082[3531:TEBOLH]2.0.CO;2
    description: Marsupial trait data
    taxaList: Marsupials
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
```
