### ISSUE TITLE
legacy OTN dataset registration 11

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#80]
legacy OTN dataset registration 11
from #45 as suggested by @bmaitner

```
-
    Timestamp: 9/17/2019 8:21:25
    datasetDOI_URL: https://doi.org/10.5061/dryad.jr3kh
    contactName: Tobias Jeppsson
    contactEmail: 
    license: CC-0
    traitList: body   size | generation  time | number  of  larval  host  plant  species | adult  activity  period | overwintering  stage  before reproduction | substrate  utilization breadth
    higherGeography: Sweden
    decimalLatitude: 
    decimalLongitude: 
    taxon: Beetles | Coleoptera | Cerambycidae
    eventDate: 
    paperDOIcitation: https://doi.org/10.1111/acv.12099
    description: We compiled information on species’ traits for all residentSwedish longhorn beetles (Coleoptera: Cerambycidae) frompublished   sources.   
    taxaList: 
    usefulClasses: IUCN red list
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 8:24:22
    datasetDOI_URL: https://doi.org/10.5061/dryad.hp269
    contactName: Katherine Eisen
    contactEmail: 
    license: CC-0
    traitList: gynodioecious
    higherGeography: Global
    decimalLatitude: 
    decimalLongitude: 
    taxon: Plantae | Angiospermae 
    eventDate: 
    paperDOIcitation: https://doi.org/10.1086/684260
    description: angiosperm-wide database of gynodioecious species
    taxaList: 
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/17/2019 8:30:45
    datasetDOI_URL: https://doi.org/10.5285/2a353d2d-c1b9-4bf7-8702-9e78910844bc
    contactName: Jon Webb
    contactEmail: 
    license: CC-BY
    traitList: habitat-related traits | feeding guilds | conservation status | biotic interactions
    higherGeography: England
    decimalLatitude: 
    decimalLongitude: 
    taxon: Invertebrates
    eventDate: 
    paperDOIcitation: https://doi.org/10.5285/2a353d2d-c1b9-4bf7-8702-9e78910844bc
    description: Contains habitat-related traits, feeding guilds, conservation status (including rarity and threat status), legal protection data and associations with other taxa for just over 11,700 invertebrates
    taxaList: 11700 invertebrates
    usefulClasses: NA
    dataStandard: 
    standardizationScripts: 
    datasetName: 
    datasetID: 
-
    Timestamp: 9/30/2019 15:42:02
    datasetDOI_URL: https://doi.org/10.5061/dryad.vk24fr1 
    contactName: Esra H. Sohlström | Malte Jochum
    contactEmail: esra.sohlstroem@idiv.de
    license:  CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
    traitList: live body mass | body length | body width | taxonomic information
    higherGeography: Tropical | Sumatra | Jambi province; Temperate | Germany | Lower Saxony
    decimalLatitude: 
    decimalLongitude: 
    taxon: Araneae | Coleoptera | Dermaptera | Dictyoptera | Diptera | Geophilomorpha | Glomerida | Hemiptera | Hymenoptera | Isopoda | Julida | Lepidoptera | Lithobiomorpha | Neuroptera | Odonata | Opiliones | Orthoptera | Polydesmida | Pseudoscorpionida | Psocoptera | Scolopendromorpha
    eventDate: 2014
    paperDOIcitation: 10.1002/ece3.4702
    description: Length-mass regression dataset to calculate live (fresh) body mass from body length, width, taxonomic group, and geographic region.
    taxaList: 
    usefulClasses: length mass regression
    dataStandard: 
    standardizationScripts: 
    datasetName: Tropical and temperate macroinvertebrate morphology Sohlström et al
    datasetID: 
```
